In [2]:
import numpy as np
import pandas as pd

In [20]:
studata={"name":["joe","smith","ram"],"year":[2012,1987,1990],"marks":[32,45,56]}
print(studata)
studata_df=pd.DataFrame(studata)
print(studata_df)
stumean=np.mean(studata_df.marks)
print(stumean)




{'name': ['joe', 'smith', 'ram'], 'year': [2012, 1987, 1990], 'marks': [32, 45, 56]}
    name  year  marks
0    joe  2012     32
1  smith  1987     45
2    ram  1990     56
44.333333333333336


In [27]:
a=np.array([[111,222],
            [333,444]])
np.ndim(a)
print(a.shape)

(2, 2)


In [29]:
a1=np.array([[[111,222],[333,444]],[[555,666],[777,888]],[[999,567],[786,765]]])
print(a1)
np.ndim(a1)
print(a1.shape)


[[[111 222]
  [333 444]]

 [[555 666]
  [777 888]]

 [[999 567]
  [786 765]]]
(3, 2, 2)


In [31]:
A = np.array([
    ["00", "01", "02", "03", "04"],
    [10, 11, 12, 13, 14],
    [20, 21, 22, 23, 24],
    [30, 31, 32, 33, 34],
    [40, 41, 42, 43, 44]
])

print(A)

[['00' '01' '02' '03' '04']
 ['10' '11' '12' '13' '14']
 ['20' '21' '22' '23' '24']
 ['30' '31' '32' '33' '34']
 ['40' '41' '42' '43' '44']]


In [40]:
print(A[0:3])
print(A[:,0:3])

print(A[0:4,0:4])

[['00' '01' '02' '03' '04']
 ['10' '11' '12' '13' '14']
 ['20' '21' '22' '23' '24']]
[['00' '01' '02']
 ['10' '11' '12']
 ['20' '21' '22']
 ['30' '31' '32']
 ['40' '41' '42']]
[['00' '01' '02' '03']
 ['10' '11' '12' '13']
 ['20' '21' '22' '23']
 ['30' '31' '32' '33']]


In [42]:
print(A[::2])

[['00' '01' '02' '03' '04']
 ['20' '21' '22' '23' '24']
 ['40' '41' '42' '43' '44']]


In [46]:
print(A[:,1:4:2])

[['01' '03']
 ['11' '13']
 ['21' '23']
 ['31' '33']
 ['41' '43']]


In [50]:
A = np.arange(12)
B = A.reshape(3, 4)

A[0] = 42
print(A)
print(B)

[42  1  2  3  4  5  6  7  8  9 10 11]
[[42  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
